# Generated by Django 6.1 on 2026-09-09 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_desc', models.TextField()),
                ('project_start', models.DateTimeField(auto_now_add=True)),
                ('project_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
