# Generated by Django 6.1 on 2026-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
