# Generated by Django 6.1 on 2026-09-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projects_project_link_projects_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_start',
            field=models.DateTimeField(),
        ),
    ]
