# Generated by Django 6.1 on 2026-09-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_experience_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_end',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_start',
        ),
        migrations.AddField(
            model_name='projects',
            name='tech_stack',
            field=models.CharField(default='Not set', max_length=255),
            preserve_default=False,
        ),
    ]
