# Generated by Django 6.1 on 2026-09-14 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_projects_project_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
